import {
  mysqlTable,
  int,
  varchar,
  text,
  double,
  float,
  datetime,
  date,
  mysqlEnum,
  tinyint,
} from "drizzle-orm/mysql-core"

export const visitors = mysqlTable("wl_customers", {
  customers_id: int("customers_id").autoincrement().primaryKey(),
  user_id: int("user_id"),
  email: varchar("email", { length: 255 }).notNull(),
  member_type: tinyint("member_type").notNull().default(0),
  member_login_type: tinyint("member_login_type").notNull().default(0),
  user_name: varchar("user_name", { length: 80 }),
  alternate_email: varchar("alternate_email", { length: 100 }),
  password: varchar("password", { length: 100 }).notNull(),
  title: varchar("title", { length: 10 }),
  first_name: varchar("first_name", { length: 32 }),
  preferred_name: varchar("preferred_name", { length: 200 }),
  preferred_language: varchar("preferred_language", { length: 50 }),
  guest_type: mysqlEnum("guest_type", ["General", "VIP", "VVIP"]).default("General"),
  last_name: varchar("last_name", { length: 32 }),
  store_name: varchar("store_name", { length: 50 }),
  gender: mysqlEnum("gender", ["Male", "Female"]),
  birth_date: date("birth_date"),
  profile_photo: varchar("profile_photo", { length: 100 }),
  phone_number: varchar("phone_number", { length: 32 }),
  mobile_number: varchar("mobile_number", { length: 32 }),
  fax_number: varchar("fax_number", { length: 32 }),
  latitude: double("latitude", { precision: 15, scale: 8 }),
  longitude: double("longitude", { precision: 15, scale: 8 }),
  address: text("address"),
  country: int("country").default(0),
  state: int("state").default(0),
  city: int("city").default(0),
  location: int("location").default(0),
  pin_code: int("pin_code"),
  ucountry_name: varchar("ucountry_name", { length: 100 }),
  ustate_name: varchar("ustate_name", { length: 100 }),
  ucity_name: varchar("ucity_name", { length: 100 }),
  utaluka_name: varchar("utaluka_name", { length: 100 }),
  umandal_name: varchar("umandal_name", { length: 100 }),
  state_id: int("state_id").notNull(),
  district_id: int("district_id").notNull(),
  taluka_id: int("taluka_id").notNull(),
  mandal_id: int("mandal_id").notNull(),
  village: varchar("village", { length: 200 }),
  uvillage_name: varchar("uvillage_name", { length: 200 }),
  shop_name: varchar("shop_name", { length: 150 }),
  shop_banner: varchar("shop_banner", { length: 100 }),
  address_line1: varchar("address_line1", { length: 200 }),
  address_line2: varchar("address_line2", { length: 200 }),
  ulocation: varchar("ulocation", { length: 100 }),
  customer_support: varchar("customer_support", { length: 100 }),
  actkey: varchar("actkey", { length: 32 }).notNull(),
  user_uq_token: varchar("user_uq_token", { length: 70 }),
  status: mysqlEnum("status", ["0", "1", "2", "3"]).notNull().default("0"),
  otp_verified: tinyint("otp_verified").default(0),
  otp_code: varchar("otp_code", { length: 6 }),
  last_status: tinyint("last_status").notNull(),
  trashed_by: int("trashed_by").notNull(),
  trashed: tinyint("trashed").notNull(),
  is_reverted: tinyint("is_reverted").notNull(),
  is_verified: mysqlEnum("is_verified", ["0", "1", "2"]).notNull().default("0"),
  is_verified_mobile: mysqlEnum("is_verified_mobile", ["0", "1"]).notNull().default("0"),
  login_type: mysqlEnum("login_type", ["normal", "facebook", "twitter"]).notNull().default("normal"),
  account_created_date: datetime("account_created_date"),
  account_updated_date: datetime("account_updated_date").notNull(),
  current_login: datetime("current_login"),
  block_time: datetime("block_time").notNull(),
  last_login_date: datetime("last_login_date"),
  ip_address: varchar("ip_address", { length: 25 }).notNull(),
  is_blocked: mysqlEnum("is_blocked", ["0", "1"]).notNull().default("0"),
  number_of_login_try: int("number_of_login_try").notNull().default(0),
  replied: mysqlEnum("replied", ["Y", "N"]).notNull().default("N"),
  verify_code: int("verify_code"),
  app_id: varchar("app_id", { length: 255 }),
  device_id: text("device_id"),
  app_type: varchar("app_type", { length: 255 }),
  temp_mobile: varchar("temp_mobile", { length: 20 }),
  temp_email: varchar("temp_email", { length: 80 }),
  is_verified_mail_once: tinyint("is_verified_mail_once").notNull().default(0),
  my_ref_code_users: int("my_ref_code_users").notNull(),
  is_import: tinyint("is_import").notNull().default(0),
  seller_rating: varchar("seller_rating", { length: 30 }),
  ship_on_time: varchar("ship_on_time", { length: 30 }),
  chat_response: varchar("chat_response", { length: 30 }),
  bank_name: varchar("bank_name", { length: 100 }),
  account_no: varchar("account_no", { length: 20 }),
  ac_holder_name: varchar("ac_holder_name", { length: 255 }).notNull(),
  branch_name: varchar("branch_name", { length: 100 }),
  ifsc_code: varchar("ifsc_code", { length: 10 }),
  qr_code: varchar("qr_code", { length: 255 }).notNull(),
  upi_id: varchar("upi_id", { length: 255 }).notNull(),
  admin_commission: float("admin_commission", { precision: 10, scale: 2 }).notNull().default(0),
  shipping_charges: int("shipping_charges").notNull().default(0),
  order_amount_for_free_shipping: int("order_amount_for_free_shipping").notNull().default(0),
  payable_amount: float("payable_amount", { precision: 10, scale: 2 }).notNull().default(0),
  paid_amount: float("paid_amount", { precision: 10, scale: 2 }).notNull().default(0),
  commission_amount: float("commission_amount", { precision: 10, scale: 2 }).notNull().default(0),
  shipping_amount: float("shipping_amount", { precision: 10, scale: 2 }).notNull().default(0),
  p_id: int("p_id"),
  ref_id: int("ref_id").notNull().default(0),
  company_name: varchar("company_name", { length: 255 }).notNull(),
  domain: varchar("domain", { length: 255 }).notNull(),
  other_domain: varchar("other_domain", { length: 255 }),
  company_logo: varchar("company_logo", { length: 255 }).notNull(),
  membership_id: int("membership_id").notNull(),
  membership_plan: varchar("membership_plan", { length: 150 }).notNull(),
  membership_plan_price: float("membership_plan_price", { precision: 10, scale: 2 }).notNull(),
  membership_plan_duration: int("membership_plan_duration").notNull(),
  plan_start_date: date("plan_start_date").notNull(),
  plan_expiry_date: date("plan_expiry_date").notNull(),
  plan_renew_date: date("plan_renew_date").notNull(),
  transaction_slip: varchar("transaction_slip", { length: 255 }).notNull(),
  old_added_company: int("old_added_company").notNull(),
  new_added_company: int("new_added_company").notNull(),
  total_added_company: int("total_added_company").notNull(),
  used_added_company: int("used_added_company").notNull(),
  remain_added_company: int("remain_added_company").notNull(),
  resume: varchar("resume", { length: 150 }),
  aadhar_number: varchar("aadhar_number", { length: 50 }),
  aadhar_image: varchar("aadhar_image", { length: 255 }),
  passport_image: varchar("passport_image", { length: 255 }),
  image1: varchar("image1", { length: 255 }),
  image2: varchar("image2", { length: 255 }),
  image3: varchar("image3", { length: 255 }),
  aadhar_verified: tinyint("aadhar_verified").default(0),
  referral_code: varchar("referral_code", { length: 100 }),
  pan_number: varchar("pan_number", { length: 50 }),
  license_number: varchar("license_number", { length: 50 }),
  voter_id_number: varchar("voter_id_number", { length: 50 }),
  aadhar_number_image: varchar("aadhar_number_image", { length: 255 }),
  pan_number_image: varchar("pan_number_image", { length: 255 }),
  license_number_image: varchar("license_number_image", { length: 255 }),
  voterid_number_image: varchar("voterid_number_image", { length: 255 }),
  worked_exp: varchar("worked_exp", { length: 255 }),
  total_work_exp: varchar("total_work_exp", { length: 255 }),
  selected_date: datetime("selected_date").notNull(),
  candidate_status: tinyint("candidate_status").notNull().default(0),
  interview_status: tinyint("interview_status").notNull(),
  updated_by: int("updated_by").notNull(),
  is_approve: mysqlEnum("is_approve", ["0", "1"]).notNull().default("0"),
  is_employee: mysqlEnum("is_employee", ["0", "1"]).notNull().default("0"),
  joining_date: date("joining_date").notNull(),
  employee_code: varchar("employee_code", { length: 150 }).notNull(),
  designation: varchar("designation", { length: 255 }).notNull(),
  salary: int("salary").notNull(),
  salary_type: varchar("salary_type", { length: 150 }).notNull(),
  job_start_time: varchar("job_start_time", { length: 150 }).notNull(),
  job_end_time: varchar("job_end_time", { length: 150 }).notNull(),
  job_time: varchar("job_time", { length: 255 }).notNull(),
  work_days_on: varchar("work_days_on", { length: 150 }).notNull(),
  work_days_off: varchar("work_days_off", { length: 150 }).notNull(),
  icard_file: varchar("icard_file", { length: 255 }).notNull(),
  offer_letter_file: varchar("offer_letter_file", { length: 255 }).notNull(),
  candidate_job_designation: varchar("candidate_job_designation", { length: 100 }),
  gst_number: varchar("gst_number", { length: 150 }),
  referral_points: int("referral_points").notNull(),
  distributor_id: int("distributor_id").notNull(),
  v_referral_code: varchar("v_referral_code", { length: 100 }),
  distributor_qr_code: varchar("distributor_qr_code", { length: 100 }),
  distributor_upi_id: varchar("distributor_upi_id", { length: 100 }),
  referral_points_value: varchar("referral_points_value", { length: 100 }).notNull(),
  blood_group: varchar("blood_group", { length: 100 }),
  illness: varchar("illness", { length: 100 }),
  age: varchar("age", { length: 100 }),
  refer_approved: mysqlEnum("refer_approved", ["1", "2"]).notNull().default("1"),
  refer__visitor_user: int("refer__visitor_user").notNull(),
  customer_qr: varchar("customer_qr", { length: 255 }),
})
